version: "3.8"  

services:
  frontend:
    container_name: mys-web-server 
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"      
    restart: unless-stopped

  backend:
    container_name: mys-backend-server
    build: 
      context: ./backend/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/demo/.env
    restart: unless-stopped
